feat: add user and film models and controllers
Nikolas7zip/java-filmorate pull request #1
Opened 2022-08-09 17:43 UTC by Nikolas7zip

Sprint 9

2022-08-09 20:22 UTC, FanaticFiz requested changes
Финальный коммент на Я.Практикуме

2022-08-09 20:22 UTC, FanaticFiz commented on pom.xml
> +	<parent>
Вечер добрый!

Итак начнем с `pom` файла. Его желательно бы "причесать": очень не хватает отделения друг от друга (пустыми строками) глобальных частей таких как parent, `properties`, `dependencies`

Хорошим тоном будет указать кодировку в `properties`
`<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

2022-08-09 20:22 UTC, FanaticFiz commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
Советую прочитать про семантическое версионирование, ну а после, проставь более адекватную версию.

2022-08-09 20:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +package ru.yandex.practicum.filmorate.controller;
Следуй единому принципу именования пакетов. Определись во множественном числе или единственном тебе сейчас кажется более уместным. Но точно не в разнобой: `controller` / `exceptions`

2022-08-09 20:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final LocalDate CINEMA_BIRTHDAY = LocalDate.of(1895, 12, 28);
Вижу что всё обильно "смазано" статиками...
Ну это так, чтобы наверняка работало? ))

Убирай это фу-фу-фу...

2022-08-09 20:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } catch (ValidationException ex) {
Ну нет, это будет не так... в этой работе не нужно ничего делать с ексепшенами. Нужно их просто бросать, а как обрабатывать будет далее по курсу.

2022-08-09 20:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return new ResponseEntity<>(newFilm, HttpStatus.OK);
О! `ResponseEntity` эт правильно, но кажется ты где то его самостоятельно нарыл? ))

2022-08-09 20:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public static void validate(final Film film) throws ValidationException {
Я видел что валидатор не подключен в pom, ты с ним не разобрался?

Ну и смотри, валидатор должен только валидировать, вот даже бросать ексепшн это не его работа.
Поэтому этот метод надо переназвать. Например в `throwIfNotValid` но, повторюсь, это не валидатор конечно...

2022-08-09 20:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private void changeBlankNameToLogin(User user) {
Вот это правильно. 

Во многих работах студенты замешивают эту логику в валидатор.
А валидатор что должен делать? ))

2022-08-09 20:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +public class ValidationException extends RuntimeException {
Сам эксепшн лучше переименовать, на `BadRequestException` поскольку в веб сервисе мы будем отвечать таким HTTP кодом на все не каретные запросы, которые выявляет валидация.

2022-08-09 20:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NonNull
@NonNull от ломбок, только кинет ошибку но не в том формате в котором это сделает аннотация от валидатора

2022-08-09 20:22 UTC, FanaticFiz commented on src/main/resources/application.properties
> +
Я буду топить за то чтобы ты сразу привыкал к написанию файла свойств для приложения в формате yaml -> application.yml

Соответственно - попрошу тебя этому следовать.
Как мини задание: посмотри как задавать порт для сервиса отличный от дефолтного и случайный.
(Сам порт менять не нужно, сломаются тесты)

2022-08-10 09:54 UTC, Nikolas7zip commented
Спасибо! Буду править.

2022-08-10 09:58 UTC, closed without merging